### ISSUE TITLE
FEATURE REQUEST - app as digital assistant

### ISSUE THREAD

**Issue by suvanbanerjee** [parallelcc/MiCTS#27]
Ni hao @parallelcc , amazing work on this app! I have a suggestion: how about turning it into a digital assistant that can be triggered by holding the home key? I’m not sure about the complexity involved in this (I’m not an Android developer), but it would definitely be a great feature to have.

**Comment by parallelcc** [comment]
Thanks for your support! Regarding this suggestion:

For non-root users, it's not possible to set micts as the digital assistant since the digital assistant is a connection to Google. You have to set Google as the digital assistant for micts to work

For root users, they can use some key mapping tools to realize triggering by holding the home key, so setting micts as the digital assistant isn't necessary either

**Comment by suvanbanerjee** [comment]
Sadly, I’m using a non-rooted device (CMF Phone 1), but the app works like magic when opened. I’ve also configured the double-click power button to trigger the circle for search. Thanks again for this app! Closing the issue.
